pull_request_rules:
  - name: assign PRs with Python files modified to jd
    conditions:
      - files~=\.java$
      - -closed
    actions:
      assign:
        add_users:
          - hasnainmakada-99
